---
pay_day: 15         # The day of the month which you are paid
weekend_bonus: 2    # Weekend bonus ( value is n * per-diem )
per_diem: 25        # Your per-diem rate
buffer: 0.15        # Buffer to cover the irregular things. (0.10 == 10%)
